[project]
name = 'Decentralized-Royalty-Management-System'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.Decentralized-Royalty-Management-System]
path = 'contracts/Decentralized-Royalty-Management-System.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
